### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by canihavethisone** [simp/pupmod-simp-auditd#159]
Can you please update to `stdlib < 9.0.0`

and change `herculesteam/augeasproviders_grub` to `puppet/augeasproviders_grub <5.0.0` as they have taken over the herculesteam release.

Thank you.

**Comment by LorryWe** [comment]
Please can Rocky 8 be added to the supported os list?

**Comment by canihavethisone** [comment]
Is there any progress on updating dependencies please? I understand this will also need to be done in simp-simplib and simp-kv to increase stdlib to v8

**Comment by op-ct** [comment]
stdlib 8.x is now supported as of #177 (as part of a framework-wide rollout)

**Comment by silug** [comment]
All dependencies were updated in #190
